"""Initial migration.

Revision ID: 0b32c8c04db8
Revises: 
Create Date: 2021-07-27 17:01:13.719031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b32c8c04db8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('todo', sa.Column('complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'complete')
    op.drop_column('todo', 'title')
    # ### end Alembic commands ###
